services:
  superset:
    image: apache/superset:latest
    environment:
      - "SUPERSET_CONFIG_PATH=/app/superset_home/superset_config.py"
      - "SUPERSET_SECRET_KEY=SUA_CHAVE_SECRETA_LONGA_E_ALEATORIA"
      - "FLASK_ENV=production"
      - "SUPERSET_VERSION=3.0.0"
      - "SUPERSET_WEBSERVER_WORKERS=4"
      - "SQLALCHEMY_DATABASE_URI=postgresql://superset:superset@db/superset"
    volumes:
      - ./superset_home:/app/superset_home
      - ./superset_data:/app/superset_data
    depends_on:
      - db
      - redis
    command: ["/bin/bash", "-c", "superset db upgrade && superset init && gunicorn --bind 0.0.0.0:8088 --access-logfile - --error-logfile - superset:app"]

  db:
    image: postgres:13
    environment:
      - "POSTGRES_USER=superset"
      - "POSTGRES_PASSWORD=superset"
      - "POSTGRES_DB=superset"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    restart: unless-stopped
